(() => {
  const lessons = {
    "6si-2-1": { title: "Lesson 1", intro: "Reading companion, activity and student worksheets.", items: [["iwb", "Interactive activity", "Lesson 1 activity", "Work through the Lesson 1 activity in your browser.", "lessons/6si/unit-1/Week%202/Lesson%201/6SI_U1_W2_L1_IWB_Toolkit.html"], ["worksheet", "Reading companion", "Reading companion", "Read alongside the Lesson 1 activity.", "lessons/6si/unit-1/Week%202/Lesson%201/6S1U1W2L1%20Reading%20Companion.jpg"], ["worksheet", "Worksheet", "Worksheet 1", "Complete the first Lesson 1 worksheet.", "lessons/6si/unit-1/Week%202/Lesson%201/6S1U1W2L1W1.png"], ["worksheet", "Worksheet", "Worksheet 2", "Complete the second Lesson 1 worksheet.", "lessons/6si/unit-1/Week%202/Lesson%201/6S1U1W2L1W2.png"], ["worksheet", "Worksheet", "Worksheet PDF", "Open the printable Lesson 1 worksheet.", "lessons/6si/unit-1/Week%202/Lesson%201/6S1U1W2L1Worksheet.pdf"]] },
    "6si-2-2": { title: "Lesson 2", items: [["iwb", "Interactive activity", "Lesson 2 activity", "Work through the Lesson 2 activity in your browser.", "lessons/6si/unit-1/Week%202/Lesson%202/6SI_U1_W2_L2_Complete_Pack/6SI_U1_W2_L2_IWB_Toolkit.html"], ["worksheet", "Worksheet", "Lesson 2 worksheet", "Open the Lesson 2 student worksheet.", "lessons/6si/unit-1/Week%202/Lesson%202/6SI_U1_W2_L2_Complete_Pack/6SI_U1_W2_L2_Worksheet.png"]] },
    "6si-2-3": { title: "Lesson 3", items: [["iwb", "Interactive activity", "Lesson 3 activity", "Work through the Lesson 3 activity in your browser.", "lessons/6si/unit-1/Week%202/Lesson%203/6SI_U1_W2_L3_IWB_Toolkit.html"], ["worksheet", "Worksheet", "Lesson 3 worksheet", "Open the Lesson 3 student worksheet.", "lessons/6si/unit-1/Week%202/Lesson%203/6SI_U1_W2_L3_Worksheet.png"]] },
    "6si-2-4": { title: "Lesson 4", items: [["iwb", "Interactive activity", "Lesson 4 activity", "Work through the Lesson 4 activity in your browser.", "lessons/6si/unit-1/Week%202/Lesson%204/6SI_U1_W2_L4_IWB_Toolkit.html"], ["worksheet", "Worksheet", "Lesson 4 worksheet", "Open the Lesson 4 student worksheet.", "lessons/6si/unit-1/Week%202/Lesson%204/6SI_U1_W2_L4_Worksheet.png"]] },
    "6si-2-5": { title: "Lesson 5", items: [["iwb", "Interactive activity", "Lesson 5 activity", "Work through the Lesson 5 activity in your browser.", "lessons/6si/unit-1/Week%202/Lesson%205/6SI_U1_W2_L5_IWB_Toolkit.html"], ["worksheet", "Worksheet", "Lesson 5 worksheet", "Open the Lesson 5 student worksheet.", "lessons/6si/unit-1/Week%202/Lesson%205/6SI_U1_W2_L5_Worksheet.png"]] },
    "6si-2-6": { title: "Lesson 6", items: [["iwb", "Interactive activity", "Lesson 6 activity", "Work through the Lesson 6 activity in your browser.", "lessons/6si/unit-1/Week%202/Lesson%206/6SI_U1_W2_L6_IWB_Toolkit.html"], ["worksheet", "Worksheet", "Lesson 6 worksheet", "Open the Lesson 6 student worksheet.", "lessons/6si/unit-1/Week%202/Lesson%206/6SI_U1_W2_L6_Worksheet.png"]] },
    "6si-2-7": { title: "Lesson 7", items: [["iwb", "Interactive activity", "Lesson 7 activity", "Work through the Lesson 7 activity in your browser.", "lessons/6si/unit-1/Week%202/Lesson%207/6SI_U1_W2_L7_IWB_Toolkit.html"], ["worksheet", "Worksheet", "Lesson 7 worksheet", "Open the Lesson 7 student worksheet.", "lessons/6si/unit-1/Week%202/Lesson%207/6SI_U1_W2_L7_Worksheet.png"]] },
    "5si-2-8": { title: "Lesson 8", intro: "Inferring character through activities and student worksheets.", items: [["iwb", "Interactive activity", "Inferring character", "Explore character inference in the Lesson 8 activity.", "lessons/5si/unit-1/Week%202/Lesson%208/5SI_U1W2L8_Inferring-Character_IWB.html"], ["iwb", "Interactive activity", "Same scene, four people", "Compare how four people can experience the same moment.", "lessons/5si/unit-1/Week%202/Lesson%208/same-scene-four-people%20(1).html"], ["iwb", "Interactive activity", "Same scene: illustrated", "Open the illustrated version of the activity.", "lessons/5si/unit-1/Week%202/Lesson%208/same-scene-four-people-illustrated%20(2).html"], ["worksheet", "Worksheet", "Worksheet 1", "Open the first Lesson 8 worksheet.", "lessons/5si/unit-1/Week%202/Lesson%208/5SIU1W2L8WS.png"], ["worksheet", "Worksheet", "Worksheet 2", "Open the second Lesson 8 worksheet.", "lessons/5si/unit-1/Week%202/Lesson%208/5SIU1W2L8WS2.png.png"], ["worksheet", "Worksheet", "Worksheet 3", "Open the third Lesson 8 worksheet.", "lessons/5si/unit-1/Week%202/Lesson%208/5SIU1W2L8WS3.png.png"]] },
    "5si-2-9": { title: "Lesson 9", intro: "Point of view activities and student worksheets.", items: [["iwb", "Interactive activity", "Point of view", "Explore point of view in the Lesson 9 activity.", "lessons/5si/unit-1/Week%202/Lesson%209/5SI_U1W2L9_Point-of-View_IWB.html"], ["iwb", "Interactive activity", "Two tellers", "Compare two illustrated tellers.", "lessons/5si/unit-1/Week%202/Lesson%209/two-tellers-illustrated.html"], ["worksheet", "Worksheet", "Worksheet 1", "Open the first Lesson 9 worksheet.", "lessons/5si/unit-1/Week%202/Lesson%209/5SIW2L9WS1.png"], ["worksheet", "Worksheet", "Worksheet 2", "Open the second Lesson 9 worksheet.", "lessons/5si/unit-1/Week%202/Lesson%209/5SIW2L9WS2.png"], ["worksheet", "Worksheet", "Worksheet 3", "Open the third Lesson 9 worksheet.", "lessons/5si/unit-1/Week%202/Lesson%209/5SIW2L9WS3.png"], ["worksheet", "Worksheet", "Worksheet 4", "Open the fourth Lesson 9 worksheet.", "lessons/5si/unit-1/Week%202/Lesson%209/5SIW2L9WS4.png"]] },
    "5si-2-10": { title: "Lesson 10", items: [["worksheet", "Worksheet", "Worksheet 1", "Open a Lesson 10 student worksheet.", "lessons/5si/unit-1/Week%202/Lesson%2010/5SIU1W2L10WS3.png"], ["worksheet", "Worksheet", "Worksheet 2", "Open a Lesson 10 student worksheet.", "lessons/5si/unit-1/Week%202/Lesson%2010/5SIU1W2L10WS4.png"], ["worksheet", "Worksheet", "Extension 1", "Open the linked student worksheet.", "lessons/5si/unit-1/Week%202/Lesson%2010/5SIU1W2L11WS1.png"], ["worksheet", "Worksheet", "Extension 2", "Open the linked student worksheet.", "lessons/5si/unit-1/Week%202/Lesson%2010/5SIU1W2L11WS2.png"]] },
    "5si-2-11": { title: "Lesson 11", intro: "Close reading practice for key events, details and effects.", items: [["iwb", "Interactive activity", "To Angkor Wat", "Practise close reading skills with the Lesson 11 classroom activity.", "lessons/5si/unit-1/Week%202/Lesson%2011/5SI-U1W2-L11-To-Angkor-Wat-IWB.html"], ...["1","2","3","4"].map(n => ["worksheet", "Worksheet", `Worksheet ${n}`, "Open the Lesson 11 student worksheet.", `lessons/5si/unit-1/Week%202/Lesson%2011/5SIU1W2L11WS${n}.png`])] },
    "5si-2-12": { title: "Lesson 12", intro: "Sequence-of-events practice with the lesson text and student worksheets.", items: [["iwb", "Interactive activity", "A Mini-Golf Gripe", "Practise sequencing with the Lesson 12 classroom activity.", "lessons/5si/unit-1/Week%202/Lesson%2012/5SI-U1W2-L12-Mini-Golf-Gripe-IWB.html"], ...["1","2","3","4"].map(n => ["worksheet", "Worksheet", `Worksheet ${n}`, "Open the Lesson 12 student worksheet.", `lessons/5si/unit-1/Week%202/Lesson%2012/5SIU1W2L12WS${n}.png`])] },
    "5si-2-13": { title: "Lesson 13", items: ["1","2","3","4"].map(n => ["worksheet", "Worksheet", `Worksheet ${n}`, "Open the Lesson 13 student worksheet.", `lessons/5si/unit-1/Week%202/Lesson%2013/5SIU1WL13WS${n}.png`]) },
    "5si-2-14": { title: "Lesson 14", items: ["1","2","3","4"].map(n => ["worksheet", "Worksheet", `Worksheet ${n}`, "Open the Lesson 14 student worksheet.", `lessons/5si/unit-1/Week%202/Lesson%2014/5SIU1WL13WS${n}.png`]) },
    "6lva-1-1": { title: "Lesson 1", items: [["iwb", "Interactive notebook", "Cahier: Week 1", "Open the Week 1 classroom notebook.", "lessons/6lva/unit-1/Week%201/Lesson%201/cahier-week1-lesson1.html"], ["iwb", "Interactive notebook", "Cahier: ordinals", "Open the ordinals classroom notebook.", "lessons/6lva/unit-1/Week%201/Lesson%201/cahier-week2-ordinals.html"], ["worksheet", "Worksheet", "Lesson 1 worksheet", "Open the Lesson 1 worksheet.", "lessons/6lva/unit-1/Week%201/Lesson%201/U1W1L1WS1.png"], ["worksheet", "Worksheet PDF", "Unit 1 Lesson 1", "Open the printable Lesson 1 document.", "lessons/6lva/unit-1/Week%201/Lesson%201/Unit%201%20Lesson%201.pdf"]] },
    "6lva-1-2": { title: "Lesson 2", items: ["1","2","3","4"].map(n => ["worksheet", "Worksheet", `Worksheet ${n}`, "Open the Lesson 2 worksheet.", `lessons/6lva/unit-1/Week%201/Lesson%202/U1L2WS${n}.png`]).concat([["worksheet", "Worksheet PDF", "Unit 1 Lesson 2", "Open the printable Lesson 2 document.", "lessons/6lva/unit-1/Week%201/Lesson%202/Unit%201%20Lesson%202.pdf"]]) },
    "6lva-1-3": { title: "Lesson 3", items: [["worksheet", "Worksheet", "Worksheet 1", "Open a Lesson 3 worksheet.", "lessons/6lva/unit-1/Week%201/Lesson%203/26a8d3f1-2eca-4d5a-a344-ec2e28e24925.png"], ["worksheet", "Worksheet", "Worksheet 2", "Open a Lesson 3 worksheet.", "lessons/6lva/unit-1/Week%201/Lesson%203/85915c0c-f12d-47c3-9d4f-27ba4de4c8c9.png"], ["worksheet", "Worksheet", "Worksheet 3", "Open a Lesson 3 worksheet.", "lessons/6lva/unit-1/Week%201/Lesson%203/90294777-d531-4bd4-a923-2c1e54c4f95f.png"], ["worksheet", "Worksheet", "Worksheet 4", "Open a Lesson 3 worksheet.", "lessons/6lva/unit-1/Week%201/Lesson%203/973c0f8f-a1e5-4b35-8345-fa6000907dd4.png"], ["worksheet", "Worksheet PDF", "Unit 1 Lesson 3", "Open the printable Lesson 3 document.", "lessons/6lva/unit-1/Week%201/Lesson%203/Unit%201%20Lesson%203.pdf"]] },
    "6lva-1-4": { title: "Lesson 4", intro: "Feelings vocabulary through facial expressions and body language.", items: [["game", "Classroom game", "Read the Feelings", "Guess three feelings from facial expressions and body language across five stages.", "lessons/6lva/unit-1/Week%201/Lesson%204/feelings-game.html"], ["worksheet", "Worksheet", "Worksheet", "Open the Lesson 4 worksheet.", "lessons/6lva/unit-1/Week%201/Lesson%204/e7d83119-7bdc-4674-86ad-a431d677a34e.png"], ["worksheet", "Worksheet", "Lesson 4 image 1", "Open the first Lesson 4 student image.", "lessons/6lva/unit-1/Week%201/Lesson%204/Gemini_Generated_Image_x0kzn5x0kzn5x0kz.jpg"], ["worksheet", "Worksheet", "Lesson 4 image 2", "Open the second Lesson 4 student image.", "lessons/6lva/unit-1/Week%201/Lesson%204/Gemini_Generated_Image_xwroj4xwroj4xwro.jpg"], ["worksheet", "Worksheet PDF", "Unit 1 Lesson 4", "Open the printable Lesson 4 document.", "lessons/6lva/unit-1/Week%201/Lesson%204/Unit%201%20Lesson%204.pdf"]] }
  };
  lessons["6si-2-2"].items.push(["iwb", "Interactive activity", "Beyond the First Glance", "Explore the Beyond the First Glance activity.", "lessons/6si/unit-1/Week%202/Lesson%202/6SI_U1_W2_L2_Complete_Pack/Beyond-the-First-Glance.html"]);
  lessons["5si-3-15"] ??= { title: "Lesson 15", intro: "Interactive classroom activities.", items: [] };
  lessons["5si-3-15"].items.push(["iwb","Interactive activity","Close reading skills: Clock Watching","Open the classroom activity.","lessons/5si/unit-1/Week%203/Lesson%2015/5SI-Close-Reading-Clock-Watching-IWB.html"]);
  lessons["5si-3-16"] ??= { title: "Lesson 16", intro: "Interactive classroom activities.", items: [] };
  lessons["5si-3-16"].items.push(["iwb","Interactive activity","Year 8 English: Inference, Reading Between the Lines","Open the classroom activity.","lessons/5si/unit-1/Week%203/Lesson%2016/Y8-W1L1-Inference-IWB.html"]);
  lessons["5si-3-17"] ??= { title: "Lesson 17", intro: "Interactive classroom activities.", items: [] };
  lessons["5si-3-17"].items.push(["iwb","Interactive activity","Year 8 English: PEE, Proving It and Explaining It","Open the classroom activity.","lessons/5si/unit-1/Week%203/Lesson%2017/Y8-W1L2-PEE-IWB.html"]);
  lessons["5si-3-18"] ??= { title: "Lesson 18", intro: "Interactive classroom activities.", items: [] };
  lessons["5si-3-18"].items.push(["iwb","Interactive activity","Year 8 English: Figurative Language, Name It, Explain It","Open the classroom activity.","lessons/5si/unit-1/Week%203/Lesson%2018/Y8-W1L3-Figurative-IWB.html"]);
  lessons["5si-3-19"] ??= { title: "Lesson 19", intro: "Interactive classroom activities.", items: [] };
  lessons["5si-3-19"].items.push(["iwb","Interactive activity","Year 8 English: Author’s Craft, Why Did the Writer Do That?","Open the classroom activity.","lessons/5si/unit-1/Week%203/Lesson%2019/Y8-W1L4-Craft-IWB.html"]);
  lessons["6si-3-16"] ??= { title: "Lesson 16", intro: "Interactive classroom activities.", items: [] };
  lessons["6si-3-16"].items.push(["iwb","Interactive activity","6SI &#183; What happens next? &#183; Lesson 2 IWB","Open the classroom activity.","lessons/6si/unit-1/Week%203/Lesson%2016/6SI_Unit1_Week3_Lesson2_IWB.html"]);
  lessons["6si-3-15"] ??= { title: "Lesson 15", intro: "Interactive classroom activities.", items: [] };
  lessons["6si-3-15"].items.push(["iwb","Interactive activity","6SI &#183; Who is the hero? &#183; IWB","Open the classroom activity.","lessons/6si/unit-1/Week%203/Lesson%2015/6SI_Unit1_Week3_Lesson1_IWB.html"]);
  lessons["6si-3-17"] ??= { title: "Lesson 17", intro: "Interactive classroom activities.", items: [] };
  lessons["6si-3-17"].items.push(["iwb","Interactive activity","6SI &#183; Inside the experience &#183; Lesson 3 IWB","Open the classroom activity.","lessons/6si/unit-1/Week%203/Lesson%2017/6SI_Unit1_Week3_Lesson3_IWB.html"]);
  lessons["6si-3-18"] ??= { title: "Lesson 18", intro: "Interactive classroom activities.", items: [] };
  lessons["6si-3-18"].items.push(["iwb","Interactive activity","6SI &#183; Step inside the moment &#183; Lesson 4 IWB","Open the classroom activity.","lessons/6si/unit-1/Week%203/Lesson%2018/6SI_Unit1_Week3_Lesson4_IWB.html"]);
  lessons["6si-3-19"] ??= { title: "Lesson 19", intro: "Interactive classroom activities.", items: [] };
  lessons["6si-3-19"].items.push(["iwb","Interactive activity","Polar Explorers Field Log","Open the classroom activity.","lessons/6si/unit-1/Week%203/Lesson%2019/Polar%20Explorers%20Field%20Log%20%281%29.html"]);
  lessons["6si-3-19"] ??= { title: "Lesson 19", intro: "Interactive classroom activities.", items: [] };
  lessons["6si-3-19"].items.push(["iwb","Interactive activity","Polar Explorers: Hero&#39;s Journey","Open the classroom activity.","lessons/6si/unit-1/Week%203/Lesson%2019/Polar%20Explorers_%20Hero%27s%20Journey%20%281%29.html"]);
  lessons["5si-2-10"] ??= { title: "Lesson 10", intro: "Interactive classroom activities.", items: [] };
  lessons["5si-2-10"].items.push(["iwb","Interactive activity","5SI English: Setting, mood, events and details","Open the classroom activity.","lessons/5si/unit-1/Week%202/Lesson%2010/5SI-U1W2-L10-L11-IWB.html"]);
  const params = new URLSearchParams(location.search);
  const key = `${params.get("class")}-${params.get("week")}-${params.get("lesson")}`;
  const lesson = lessons[key];
  const className = (params.get("class") || "").toUpperCase();
  const week = params.get("week");
  const fallback = "index.html";
  if (!lesson || !className || !week) { location.replace(fallback); return; }
  const weekPage = `${params.get("class")}-unit-1-week-${week}.html`;
  document.title = `${lesson.title} | ${className} | The Learning Deck`;
  document.getElementById("lesson-kicker").textContent = `${className} · Unit 1 · Week ${week} · ${lesson.title}`;
  document.getElementById("lesson-title").textContent = lesson.title;
  document.getElementById("lesson-intro").textContent = lesson.intro || "Interactive activities and student worksheets.";
  document.getElementById("resource-heading").textContent = `${lesson.title} resources`;
  document.getElementById("back-link").href = weekPage;
  document.getElementById("back-link").firstElementChild.textContent = `${className} · Unit 1 · Week ${week}`;
  document.getElementById("resource-grid").innerHTML = lesson.items.map(([type, label, title, copy, href], index) => `<a class="resource-card resource-${type}" href="${href}" target="_blank" rel="noopener"><span class="number">${String(index + 1).padStart(2, "0")}</span><span class="icon" aria-hidden="true">${type === "iwb" ? "≋" : "◌"}</span><p class="eyebrow">${label}</p><h3>${title}</h3><p>${copy}</p><span class="action">${type === "iwb" ? "Open activity" : "Open worksheet"} <b>→</b></span></a>`).join("");
})();
