(() => {
  const lessons = {
    "6si-2-1": { title: "Lesson 1", intro: "Reading companion, activity and student worksheets.", items: [["iwb", "Interactive activity", "Lesson 1 activity", "Work through the Lesson 1 activity in your browser.", "lessons/6si/unit-1/Week%202/Lesson%201/6SI_U1_W2_L1_IWB_Toolkit.html"], ["worksheet", "Reading companion", "Reading companion", "Read alongside the Lesson 1 activity.", "lessons/6si/unit-1/Week%202/Lesson%201/6S1U1W2L1%20Reading%20Companion.jpg"], ["worksheet", "Worksheet", "Worksheet 1", "Complete the first Lesson 1 worksheet.", "lessons/6si/unit-1/Week%202/Lesson%201/6S1U1W2L1W1.png"], ["worksheet", "Worksheet", "Worksheet 2", "Complete the second Lesson 1 worksheet.", "lessons/6si/unit-1/Week%202/Lesson%201/6S1U1W2L1W2.png"], ["worksheet", "Worksheet", "Worksheet PDF", "Open the printable Lesson 1 worksheet.", "lessons/6si/unit-1/Week%202/Lesson%201/6S1U1W2L1Worksheet.pdf"]] },
    "6si-2-2": { title: "Lesson 2", items: [["iwb", "Interactive activity", "Lesson 2 activity", "Work through the Lesson 2 activity in your browser.", "lessons/6si/unit-1/Week%202/Lesson%202/6SI_U1_W2_L2_Complete_Pack/6SI_U1_W2_L2_IWB_Toolkit.html"], ["worksheet", "Worksheet", "Lesson 2 worksheet", "Open the Lesson 2 student worksheet.", "lessons/6si/unit-1/Week%202/Lesson%202/6SI_U1_W2_L2_Complete_Pack/6SI_U1_W2_L2_Worksheet.png"]] },
    "6si-2-3": { title: "Lesson 3", items: [["iwb", "Interactive activity", "Lesson 3 activity", "Work through the Lesson 3 activity in your browser.", "lessons/6si/unit-1/Week%202/Lesson%203/6SI_U1_W2_L3_IWB_Toolkit.html"], ["worksheet", "Worksheet", "Lesson 3 worksheet", "Open the Lesson 3 student worksheet.", "lessons/6si/unit-1/Week%202/Lesson%203/6SI_U1_W2_L3_Worksheet.png"]] },
    "6si-2-4": { title: "Lesson 4", items: [["iwb", "Interactive activity", "Lesson 4 activity", "Work through the Lesson 4 activity in your browser.", "lessons/6si/unit-1/Week%202/Lesson%204/6SI_U1_W2_L4_IWB_Toolkit.html"], ["worksheet", "Worksheet", "Lesson 4 worksheet", "Open the Lesson 4 student worksheet.", "lessons/6si/unit-1/Week%202/Lesson%204/6SI_U1_W2_L4_Worksheet.png"]] },
    "6si-2-5": { title: "Lesson 5", items: [["iwb", "Interactive activity", "Lesson 5 activity", "Work through the Lesson 5 activity in your browser.", "lessons/6si/unit-1/Week%202/Lesson%205/6SI_U1_W2_L5_IWB_Toolkit.html"], ["worksheet", "Worksheet", "Lesson 5 worksheet", "Open the Lesson 5 student worksheet.", "lessons/6si/unit-1/Week%202/Lesson%205/6SI_U1_W2_L5_Worksheet.png"]] },
    "6si-2-6": { title: "Lesson 6", items: [["iwb", "Interactive activity", "Lesson 6 activity", "Work through the Lesson 6 activity in your browser.", "lessons/6si/unit-1/Week%202/Lesson%206/6SI_U1_W2_L6_IWB_Toolkit.html"], ["worksheet", "Worksheet", "Lesson 6 worksheet", "Open the Lesson 6 student worksheet.", "lessons/6si/unit-1/Week%202/Lesson%206/6SI_U1_W2_L6_Worksheet.png"]] },
    "6si-2-7": { title: "Lesson 7", items: [["iwb", "Interactive activity", "Lesson 7 activity", "Work through the Lesson 7 activity in your browser.", "lessons/6si/unit-1/Week%202/Lesson%207/6SI_U1_W2_L7_IWB_Toolkit.html"], ["worksheet", "Worksheet", "Lesson 7 worksheet", "Open the Lesson 7 student worksheet.", "lessons/6si/unit-1/Week%202/Lesson%207/6SI_U1_W2_L7_Worksheet.png"]] },
    "5si-2-8": { title: "Lesson 8", intro: "Inferring character through activities and student worksheets.", items: [["iwb", "Interactive activity", "Inferring character", "Explore character inference in the Lesson 8 activity.", "lessons/5si/unit-1/Week%202/Lesson%208/5SI_U1W2L8_Inferring-Character_IWB.html"], ["iwb", "Interactive activity", "Same scene, four people", "Compare how four people can experience the same moment.", "lessons/5si/unit-1/Week%202/Lesson%208/same-scene-four-people%20(1).html"], ["iwb", "Interactive activity", "Same scene: illustrated", "Open the illustrated version of the activity.", "lessons/5si/unit-1/Week%202/Lesson%208/same-scene-four-people-illustrated%20(2).html"], ["worksheet", "Worksheet", "Worksheet 1", "Open the first Lesson 8 worksheet.", "lessons/5si/unit-1/Week%202/Lesson%208/5SIU1W2L8WS.png"], ["worksheet", "Worksheet", "Worksheet 2", "Open the second Lesson 8 worksheet.", "lessons/5si/unit-1/Week%202/Lesson%208/5SIU1W2L8WS2.png.png"], ["worksheet", "Worksheet", "Worksheet 3", "Open the third Lesson 8 worksheet.", "lessons/5si/unit-1/Week%202/Lesson%208/5SIU1W2L8WS3.png.png"]] },
    "5si-2-9": { title: "Lesson 9", intro: "Point of view activities and student worksheets.", items: [["iwb", "Interactive activity", "Point of view", "Explore point of view in the Lesson 9 activity.", "lessons/5si/unit-1/Week%202/Lesson%209/5SI_U1W2L9_Point-of-View_IWB.html"], ["iwb", "Interactive activity", "Two tellers", "Compare two illustrated tellers.", "lessons/5si/unit-1/Week%202/Lesson%209/two-tellers-illustrated.html"], ["worksheet", "Worksheet", "Worksheet 1", "Open the first Lesson 9 worksheet.", "lessons/5si/unit-1/Week%202/Lesson%209/5SIW2L9WS1.png"], ["worksheet", "Worksheet", "Worksheet 2", "Open the second Lesson 9 worksheet.", "lessons/5si/unit-1/Week%202/Lesson%209/5SIW2L9WS2.png"], ["worksheet", "Worksheet", "Worksheet 3", "Open the third Lesson 9 worksheet.", "lessons/5si/unit-1/Week%202/Lesson%209/5SIW2L9WS3.png"], ["worksheet", "Worksheet", "Worksheet 4", "Open the fourth Lesson 9 worksheet.", "lessons/5si/unit-1/Week%202/Lesson%209/5SIW2L9WS4.png"]] },
    "5si-2-10": { title: "Lesson 10", items: [["worksheet", "Worksheet", "Worksheet 1", "Open a Lesson 10 student worksheet.", "lessons/5si/unit-1/Week%202/Lesson%2010/5SIU1W2L10WS3.png"], ["worksheet", "Worksheet", "Worksheet 2", "Open a Lesson 10 student worksheet.", "lessons/5si/unit-1/Week%202/Lesson%2010/5SIU1W2L10WS4.png"], ["worksheet", "Worksheet", "Extension 1", "Open the linked student worksheet.", "lessons/5si/unit-1/Week%202/Lesson%2010/5SIU1W2L11WS1.png"], ["worksheet", "Worksheet", "Extension 2", "Open the linked student worksheet.", "lessons/5si/unit-1/Week%202/Lesson%2010/5SIU1W2L11WS2.png"]] },
    "5si-2-11": { title: "Lesson 11", intro: "Close reading practice for key events, details and effects.", items: [["iwb", "Interactive activity", "To Angkor Wat", "Practise close reading skills with the Lesson 11 classroom activity.", "lessons/5si/unit-1/Week%202/Lesson%2011/5SI-U1W2-L11-To-Angkor-Wat-IWB.html"], ...["1","2","3","4"].map(n => ["worksheet", "Worksheet", `Worksheet ${n}`, "Open the Lesson 11 student worksheet.", `lessons/5si/unit-1/Week%202/Lesson%2011/5SIU1W2L11WS${n}.png`])] },
    "5si-2-12": { title: "Lesson 12", intro: "Sequence-of-events practice with the lesson text and student worksheets.", items: [["iwb", "Interactive activity", "A Mini-Golf Gripe", "Practise sequencing with the Lesson 12 classroom activity.", "lessons/5si/unit-1/Week%202/Lesson%2012/5SI-U1W2-L12-Mini-Golf-Gripe-IWB.html"], ...["1","2","3","4"].map(n => ["worksheet", "Worksheet", `Worksheet ${n}`, "Open the Lesson 12 student worksheet.", `lessons/5si/unit-1/Week%202/Lesson%2012/5SIU1W2L12WS${n}.png`])] },
    "5si-2-13": { title: "Lesson 13", items: ["1","2","3","4"].map(n => ["worksheet", "Worksheet", `Worksheet ${n}`, "Open the Lesson 13 student worksheet.", `lessons/5si/unit-1/Week%202/Lesson%2013/5SIU1WL13WS${n}.png`]) },
    "5si-2-14": { title: "Lesson 14", items: ["1","2","3","4"].map(n => ["worksheet", "Worksheet", `Worksheet ${n}`, "Open the Lesson 14 student worksheet.", `lessons/5si/unit-1/Week%202/Lesson%2014/5SIU1WL13WS${n}.png`]) },
    "6lva-1-1": { title: "Lesson 1", items: [["iwb", "Interactive notebook", "Cahier: Week 1", "Open the Week 1 classroom notebook.", "lessons/6lva/unit-1/Week%201/Lesson%201/cahier-week1-lesson1.html"], ["iwb", "Interactive notebook", "Cahier: ordinals", "Open the ordinals classroom notebook.", "lessons/6lva/unit-1/Week%201/Lesson%201/cahier-week2-ordinals.html"], ["worksheet", "Worksheet", "Lesson 1 worksheet", "Open the Lesson 1 worksheet.", "lessons/6lva/unit-1/Week%201/Lesson%201/U1W1L1WS1.png"], ["worksheet", "Worksheet PDF", "Unit 1 Lesson 1", "Open the printable Lesson 1 document.", "lessons/6lva/unit-1/Week%201/Lesson%201/Unit%201%20Lesson%201.pdf"]] },
    "6lva-1-2": { title: "Lesson 2", items: ["1","2","3","4"].map(n => ["worksheet", "Worksheet", `Worksheet ${n}`, "Open the Lesson 2 worksheet.", `lessons/6lva/unit-1/Week%201/Lesson%202/U1L2WS${n}.png`]).concat([["worksheet", "Worksheet PDF", "Unit 1 Lesson 2", "Open the printable Lesson 2 document.", "lessons/6lva/unit-1/Week%201/Lesson%202/Unit%201%20Lesson%202.pdf"]]) },
    "6lva-1-3": { title: "Lesson 3", items: [["worksheet", "Worksheet", "Worksheet 1", "Open a Lesson 3 worksheet.", "lessons/6lva/unit-1/Week%201/Lesson%203/26a8d3f1-2eca-4d5a-a344-ec2e28e24925.png"], ["worksheet", "Worksheet", "Worksheet 2", "Open a Lesson 3 worksheet.", "lessons/6lva/unit-1/Week%201/Lesson%203/85915c0c-f12d-47c3-9d4f-27ba4de4c8c9.png"], ["worksheet", "Worksheet", "Worksheet 3", "Open a Lesson 3 worksheet.", "lessons/6lva/unit-1/Week%201/Lesson%203/90294777-d531-4bd4-a923-2c1e54c4f95f.png"], ["worksheet", "Worksheet", "Worksheet 4", "Open a Lesson 3 worksheet.", "lessons/6lva/unit-1/Week%201/Lesson%203/973c0f8f-a1e5-4b35-8345-fa6000907dd4.png"], ["worksheet", "Worksheet PDF", "Unit 1 Lesson 3", "Open the printable Lesson 3 document.", "lessons/6lva/unit-1/Week%201/Lesson%203/Unit%201%20Lesson%203.pdf"]] },
    "6lva-1-4": { title: "Lesson 4", intro: "Feelings vocabulary through facial expressions and body language.", items: [["game", "Classroom game", "Read the Feelings", "Guess three feelings from facial expressions and body language across five stages.", "lessons/6lva/unit-1/Week%201/Lesson%204/feelings-game.html"], ["worksheet", "Worksheet", "Worksheet", "Open the Lesson 4 worksheet.", "lessons/6lva/unit-1/Week%201/Lesson%204/e7d83119-7bdc-4674-86ad-a431d677a34e.png"], ["worksheet", "Worksheet", "Lesson 4 image 1", "Open the first Lesson 4 student image.", "lessons/6lva/unit-1/Week%201/Lesson%204/Gemini_Generated_Image_x0kzn5x0kzn5x0kz.jpg"], ["worksheet", "Worksheet", "Lesson 4 image 2", "Open the second Lesson 4 student image.", "lessons/6lva/unit-1/Week%201/Lesson%204/Gemini_Generated_Image_xwroj4xwroj4xwro.jpg"], ["worksheet", "Worksheet PDF", "Unit 1 Lesson 4", "Open the printable Lesson 4 document.", "lessons/6lva/unit-1/Week%201/Lesson%204/Unit%201%20Lesson%204.pdf"]] }
  };
  lessons["6si-2-2"].items.push(["iwb", "Interactive activity", "Beyond the First Glance", "Explore the Beyond the First Glance activity.", "lessons/6si/unit-1/Week%202/Lesson%202/6SI_U1_W2_L2_Complete_Pack/Beyond-the-First-Glance.html"]);
  lessons["5si-3-15"] ??= { title: "Lesson 15", intro: "Interactive classroom activities.", items: [] };
  lessons["5si-3-15"].items.push(["iwb","Interactive activity","Close reading skills: Clock Watching","Open the classroom activity.","lessons/5si/unit-1/Week%203/Lesson%2015/5SI-Close-Reading-Clock-Watching-IWB.html"]);
  lessons["5si-3-16"] ??= { title: "Lesson 16", intro: "Interactive classroom activities.", items: [] };
  lessons["5si-3-16"].items.push(["iwb","Interactive activity","Year 8 English: Inference, Reading Between the Lines","Open the classroom activity.","lessons/5si/unit-1/Week%203/Lesson%2016/Y8-W1L1-Inference-IWB.html"]);
  lessons["5si-3-17"] ??= { title: "Lesson 17", intro: "Interactive classroom activities.", items: [] };
  lessons["5si-3-17"].items.push(["iwb","Interactive activity","Year 8 English: PEE, Proving It and Explaining It","Open the classroom activity.","lessons/5si/unit-1/Week%203/Lesson%2017/Y8-W1L2-PEE-IWB.html"]);
  lessons["5si-3-18"] ??= { title: "Lesson 18", intro: "Interactive classroom activities.", items: [] };
  lessons["5si-3-18"].items.push(["iwb","Interactive activity","Year 8 English: Figurative Language, Name It, Explain It","Open the classroom activity.","lessons/5si/unit-1/Week%203/Lesson%2018/Y8-W1L3-Figurative-IWB.html"]);
  lessons["5si-3-19"] ??= { title: "Lesson 19", intro: "Interactive classroom activities.", items: [] };
  lessons["5si-3-19"].items.push(["iwb","Interactive activity","Year 8 English: Author’s Craft, Why Did the Writer Do That?","Open the classroom activity.","lessons/5si/unit-1/Week%203/Lesson%2019/Y8-W1L4-Craft-IWB.html"]);
  lessons["6si-3-16"] ??= { title: "Lesson 16", intro: "Interactive classroom activities.", items: [] };
  lessons["6si-3-16"].items.push(["iwb","Interactive activity","6SI &#183; What happens next? &#183; Lesson 2 IWB","Open the classroom activity.","lessons/6si/unit-1/Week%203/Lesson%2016/6SI_Unit1_Week3_Lesson2_IWB.html"]);
  lessons["6si-3-15"] ??= { title: "Lesson 15", intro: "Interactive classroom activities.", items: [] };
  lessons["6si-3-15"].items.push(["iwb","Interactive activity","6SI &#183; Who is the hero? &#183; IWB","Open the classroom activity.","lessons/6si/unit-1/Week%203/Lesson%2015/6SI_Unit1_Week3_Lesson1_IWB.html"]);
  lessons["6si-3-17"] ??= { title: "Lesson 17", intro: "Interactive classroom activities.", items: [] };
  lessons["6si-3-17"].items.push(["iwb","Interactive activity","6SI &#183; Inside the experience &#183; Lesson 3 IWB","Open the classroom activity.","lessons/6si/unit-1/Week%203/Lesson%2017/6SI_Unit1_Week3_Lesson3_IWB.html"]);
  lessons["6si-3-18"] ??= { title: "Lesson 18", intro: "Interactive classroom activities.", items: [] };
  lessons["6si-3-18"].items.push(["iwb","Interactive activity","6SI &#183; Step inside the moment &#183; Lesson 4 IWB","Open the classroom activity.","lessons/6si/unit-1/Week%203/Lesson%2018/6SI_Unit1_Week3_Lesson4_IWB.html"]);
  lessons["6si-3-19"] ??= { title: "Lesson 19", intro: "Interactive classroom activities.", items: [] };
  lessons["6si-3-19"].items.push(["iwb","Interactive activity","Polar Explorers Field Log","Open the classroom activity.","lessons/6si/unit-1/Week%203/Lesson%2019/Polar%20Explorers%20Field%20Log%20%281%29.html"]);
  lessons["6si-3-19"] ??= { title: "Lesson 19", intro: "Interactive classroom activities.", items: [] };
  lessons["6si-3-19"].items.push(["iwb","Interactive activity","Polar Explorers: Hero&#39;s Journey","Open the classroom activity.","lessons/6si/unit-1/Week%203/Lesson%2019/Polar%20Explorers_%20Hero%27s%20Journey%20%281%29.html"]);
  lessons["5si-2-10"] ??= { title: "Lesson 10", intro: "Interactive classroom activities.", items: [] };
  lessons["5si-2-10"].items.push(["iwb","Interactive activity","5SI English: Setting, mood, events and details","Open the classroom activity.","lessons/5si/unit-1/Week%202/Lesson%2010/5SI-U1W2-L10-L11-IWB.html"]);
  lessons["6lva-2-1"] = {"title":"Lesson 1","items":[["worksheet","Worksheet image","Lesson Image 1","Open the Lesson 1 learning material.","lessons/6lva/unit-1/Week%202/Lesson%201/72318a83-479d-4053-8c11-239c7ed9b695.png"],["worksheet","Worksheet image","Lesson Image 2","Open the Lesson 1 learning material.","lessons/6lva/unit-1/Week%202/Lesson%201/823b4b45-839c-413e-836f-f70da06ce89b.png"],["worksheet","Worksheet image","Lesson Image 3","Open the Lesson 1 learning material.","lessons/6lva/unit-1/Week%202/Lesson%201/9cd3e146-b955-453c-87d7-e0a39d20b730.png"],["worksheet","Worksheet PDF","Body Parts","Open the Lesson 1 learning material.","lessons/6lva/unit-1/Week%202/Lesson%201/Body-Parts.pdf"],["worksheet","Worksheet PDF","Countries and Nationalities","Open the Lesson 1 learning material.","lessons/6lva/unit-1/Week%202/Lesson%201/Countries-and-Nationalities-Illustrated.pdf"],["worksheet","Worksheet image","Days, Months and Years","Open the Lesson 1 learning material.","lessons/6lva/unit-1/Week%202/Lesson%201/Days-Months-Years.png"],["worksheet","Worksheet image","Lesson Image 4","Open the Lesson 1 learning material.","lessons/6lva/unit-1/Week%202/Lesson%201/ec8bca95-fb35-40f5-9be2-ac3b8f138948.png"],["worksheet","Worksheet image","Lesson Image 5","Open the Lesson 1 learning material.","lessons/6lva/unit-1/Week%202/Lesson%201/Gemini_Generated_Image_kg29dqkg29dqkg29.jpg"],["worksheet","Worksheet image","Queen Elizabeth II: Speaking Recap","Open the Lesson 1 learning material.","lessons/6lva/unit-1/Week%202/Lesson%201/Queen-Elizabeth-II-Speaking-Recap.png"],["worksheet","Worksheet image","Worksheet 1","Open the Lesson 1 learning material.","lessons/6lva/unit-1/Week%202/Lesson%201/U1W2L1WS1.png"],["worksheet","Worksheet image","Worksheet 2","Open the Lesson 1 learning material.","lessons/6lva/unit-1/Week%202/Lesson%201/U1W2L1WS2.png"],["worksheet","Worksheet PDF","Printable Worksheet","Open the Lesson 1 learning material.","lessons/6lva/unit-1/Week%202/Lesson%201/Worksheet.pdf"]],"intro":"Vocabulary, speaking activities and student worksheets."};
  lessons["5si-3-15"] ??= { title: "Lesson 15", items: [] };
  lessons["5si-3-15"].items.push(["worksheet","Student material","Practice worksheet 1","Open the classroom material.","lessons/5si/unit-1/Week%203/Lesson%2015/1b12f858-c5a8-4751-8390-28559d755585.png"]);
  lessons["5si-3-16"] ??= { title: "Lesson 16", items: [] };
  lessons["5si-3-16"].items.push(["worksheet","Student material","Practice worksheet 2","Open the classroom material.","lessons/5si/unit-1/Week%203/Lesson%2016/3bf06d2d-ec51-4d3a-918b-84e982f43e74.png"]);
  lessons["5si-3-16"] ??= { title: "Lesson 16", items: [] };
  lessons["5si-3-16"].items.push(["worksheet","Student material","Practice worksheet 3","Open the classroom material.","lessons/5si/unit-1/Week%203/Lesson%2016/5b954b3e-a8fa-4968-9975-5e9c95e4f878.png"]);
  lessons["5si-3-16"] ??= { title: "Lesson 16", items: [] };
  lessons["5si-3-16"].items.push(["worksheet","Student material","5SIU1L16WS1","Open the classroom material.","lessons/5si/unit-1/Week%203/Lesson%2016/5SIU1L16WS1.png"]);
  lessons["5si-3-15"] ??= { title: "Lesson 15", items: [] };
  lessons["5si-3-15"].items.push(["worksheet","Student material","Practice worksheet 5","Open the classroom material.","lessons/5si/unit-1/Week%203/Lesson%2015/6c2cd3f2-add6-4751-8886-824856964e5a.png"]);
  lessons["5si-3-15"] ??= { title: "Lesson 15", items: [] };
  lessons["5si-3-15"].items.push(["worksheet","Student material","Practice worksheet 6","Open the classroom material.","lessons/5si/unit-1/Week%203/Lesson%2015/8c65444c-c37f-4d5a-9646-5b5edd189f1e.png"]);
  lessons["5si-3-16"] ??= { title: "Lesson 16", items: [] };
  lessons["5si-3-16"].items.push(["worksheet","Student material","Practice worksheet 7","Open the classroom material.","lessons/5si/unit-1/Week%203/Lesson%2016/a2dd30b7-f216-4265-a111-8033606dbe09.png"]);
  lessons["5si-3-15"] ??= { title: "Lesson 15", items: [] };
  lessons["5si-3-15"].items.push(["worksheet","Student material","Close Reading Practice   The Learning Deck","Open the classroom material.","lessons/5si/unit-1/Week%203/Lesson%2015/Close%20Reading%20Practice%20_%20The%20Learning%20Deck.pdf"]);
  lessons["5si-3-16"] ??= { title: "Lesson 16", items: [] };
  lessons["5si-3-16"].items.push(["worksheet","Student material","Practice worksheet 9","Open the classroom material.","lessons/5si/unit-1/Week%203/Lesson%2016/e4b24d12-45ca-409f-90d4-ab43536564c8.png"]);
  lessons["5si-3-15"] ??= { title: "Lesson 15", items: [] };
  lessons["5si-3-15"].items.push(["worksheet","Student material","Practice worksheet 10","Open the classroom material.","lessons/5si/unit-1/Week%203/Lesson%2015/f89964d6-03ae-4c03-a7f6-dba88584e26d.png"]);
  lessons["5si-3-17"] ??= { title: "Lesson 17", items: [] };
  lessons["5si-3-17"].items.push(["worksheet","Student material","W1L2 PEE Worksheet","Open the classroom material.","lessons/5si/unit-1/Week%203/Lesson%2017/W1L2_PEE_Worksheet.pdf"]);
  lessons["5si-3-18"] ??= { title: "Lesson 18", items: [] };
  lessons["5si-3-18"].items.push(["worksheet","Student material","W1L3 Figurative Worksheet","Open the classroom material.","lessons/5si/unit-1/Week%203/Lesson%2018/W1L3_Figurative_Worksheet.pdf"]);
  lessons["5si-3-19"] ??= { title: "Lesson 19", items: [] };
  lessons["5si-3-19"].items.push(["worksheet","Student material","W1L4 Craft Worksheet","Open the classroom material.","lessons/5si/unit-1/Week%203/Lesson%2019/W1L4_Craft_Worksheet.pdf"]);
  lessons["5si-3-materials"] ??= { title: "Week materials", items: [] };
  lessons["5si-3-materials"].items.push(["worksheet","Student material","W1L5 Vocab Worksheet","Open the classroom material.","lessons/5si/unit-1/Week%203/W1L5_Vocab_Worksheet.pdf"]);
  lessons["5si-3-materials"] ??= { title: "Week materials", items: [] };
  lessons["5si-3-materials"].items.push(["worksheet","Student material","W1L6 Inference2 Worksheet","Open the classroom material.","lessons/5si/unit-1/Week%203/W1L6_Inference2_Worksheet.pdf"]);
  lessons["5si-3-materials"] ??= { title: "Week materials", items: [] };
  lessons["5si-3-materials"].items.push(["iwb","Interactive activity","Year 8 English: Words in Context, and What Words Point To","Open the classroom material.","lessons/5si/unit-1/Week%203/Y8-W1L5-Vocab-IWB.html"]);
  lessons["5si-3-materials"] ??= { title: "Week materials", items: [] };
  lessons["5si-3-materials"].items.push(["iwb","Interactive activity","Year 8 English: Inference 2, Putting Clues Together","Open the classroom material.","lessons/5si/unit-1/Week%203/Y8-W1L6-Inference2-IWB.html"]);
  lessons["5si-4-materials"] ??= { title: "Week materials", items: [] };
  lessons["5si-4-materials"].items.push(["worksheet","Student material","W1L7 MiniCheck Worksheet (1)","Open the classroom material.","lessons/5si/unit-1/Week%204/W1L7_MiniCheck_Worksheet%20%281%29.pdf"]);
  lessons["5si-4-materials"] ??= { title: "Week materials", items: [] };
  lessons["5si-4-materials"].items.push(["worksheet","Student material","W2L1 NonFiction Worksheet","Open the classroom material.","lessons/5si/unit-1/Week%204/W2L1_NonFiction_Worksheet.pdf"]);
  lessons["5si-4-materials"] ??= { title: "Week materials", items: [] };
  lessons["5si-4-materials"].items.push(["iwb","Interactive activity","Year 8 English: Inference 2, Putting Clues Together","Open the classroom material.","lessons/5si/unit-1/Week%204/Y8-W1L6-Inference2-IWB.html"]);
  lessons["5si-4-materials"] ??= { title: "Week materials", items: [] };
  lessons["5si-4-materials"].items.push(["iwb","Interactive activity","Year 8 English: Mixed Mini-Check, All Six Skills","Open the classroom material.","lessons/5si/unit-1/Week%204/Y8-W1L7-MiniCheck-IWB.html"]);
  lessons["5si-4-materials"] ??= { title: "Week materials", items: [] };
  lessons["5si-4-materials"].items.push(["iwb","Interactive activity","Year 8 English: Inference in Non-Fiction, Reading the Spin","Open the classroom material.","lessons/5si/unit-1/Week%204/Y8-W2L1-NonFiction-IWB.html"]);
  lessons["6si-3-16"] ??= { title: "Lesson 16", items: [] };
  lessons["6si-3-16"].items.push(["worksheet","Student material","6SI Unit1 Week3 Lesson2 Worksheet","Open the classroom material.","lessons/6si/unit-1/Week%203/Lesson%2016/6SI_Unit1_Week3_Lesson2_Worksheet.png"]);
  lessons["6si-3-17"] ??= { title: "Lesson 17", items: [] };
  lessons["6si-3-17"].items.push(["worksheet","Student material","6SI Unit1 Week3 Lesson3 Worksheet","Open the classroom material.","lessons/6si/unit-1/Week%203/Lesson%2017/6SI_Unit1_Week3_Lesson3_Worksheet.png"]);
  lessons["6si-3-18"] ??= { title: "Lesson 18", items: [] };
  lessons["6si-3-18"].items.push(["worksheet","Student material","6SI Unit1 Week3 Lesson4 Worksheet","Open the classroom material.","lessons/6si/unit-1/Week%203/Lesson%2018/6SI_Unit1_Week3_Lesson4_Worksheet.png"]);
  lessons["6si-3-15"] ??= { title: "Lesson 15", items: [] };
  lessons["6si-3-15"].items.push(["worksheet","Student material","U1WS15","Open the classroom material.","lessons/6si/unit-1/Week%203/Lesson%2015/U1WS15.png"]);
  lessons["6si-4-materials"] ??= { title: "Week materials", items: [] };
  lessons["6si-4-materials"].items.push(["iwb","Interactive activity","6SI &#183; Hero’s Journey &#183; Lesson 1 &#183; Call to Adventure","Open the classroom material.","lessons/6si/unit-1/Week%204/6SI_Hero_Journey_L1_Call_to_Adventure_IWB.html"]);
  lessons["6si-4-materials"] ??= { title: "Week materials", items: [] };
  lessons["6si-4-materials"].items.push(["iwb","Interactive activity","6SI &#183; Hero’s Journey &#183; Lesson 2 &#183; Into the Unknown","Open the classroom material.","lessons/6si/unit-1/Week%204/6SI_Hero_Journey_L2_Into_the_Unknown_IWB.html"]);
  lessons["6si-4-materials"] ??= { title: "Week materials", items: [] };
  lessons["6si-4-materials"].items.push(["iwb","Interactive activity","6SI &#183; SPAG &#183; Clauses and Semicolons","Open the classroom material.","lessons/6si/unit-1/Week%204/6SI_Unit1_SPAG_Clauses_and_Semicolons_IWB.html"]);
  lessons["6si-4-materials"] ??= { title: "Week materials", items: [] };
  lessons["6si-4-materials"].items.push(["iwb","Interactive activity","6SI &#183; Unit 1 Week 4 &#183; Unexpected Encounters","Open the classroom material.","lessons/6si/unit-1/Week%204/6SI_Unit1_Week4_Lesson1_Unexpected_Encounters_IWB_v3.html"]);
  lessons["6si-4-materials"] ??= { title: "Week materials", items: [] };
  lessons["6si-4-materials"].items.push(["worksheet","Student material","Eight Panel Storyboard Worksheet","Open the classroom material.","lessons/6si/unit-1/Week%204/Eight-Panel%20Storyboard%20Worksheet.png"]);
  lessons["6lva-2-1"] ??= { title: "Lesson 1", items: [] };
  lessons["6lva-2-1"].items.push(["iwb","Interactive activity","Meet Noor","Open the classroom material.","lessons/6lva/unit-1/Week%202/Lesson%201/Meet%20Noor.html"]);
  lessons["5si-5-materials"] = {"items":[["worksheet","Student material","W2L4 CraftCompare Worksheet","Open the classroom material.","lessons/5si/unit-1/Week%205/W2L4_CraftCompare_Worksheet.pdf"],["worksheet","Student material","W2L5 VocabPace Worksheet","Open the classroom material.","lessons/5si/unit-1/Week%205/W2L5_VocabPace_Worksheet.pdf"],["worksheet","Student material","W2L6 LevelUp Worksheet","Open the classroom material.","lessons/5si/unit-1/Week%205/W2L6_LevelUp_Worksheet.pdf"],["iwb","Class video","Why Did the Writer Do That","Open the classroom material.","lessons/5si/unit-1/Week%205/Why_Did_the_Writer_Do_That.mp4"],["iwb","Interactive activity","Year 8 English: Author’s Craft, Compare the Choices","Open the classroom material.","lessons/5si/unit-1/Week%205/Y8-W2L4-CraftCompare-IWB.html"],["iwb","Interactive activity","Year 8 English: Word Questions at Exam Speed","Open the classroom material.","lessons/5si/unit-1/Week%205/Y8-W2L5-VocabPace-IWB.html"],["iwb","Interactive activity","Year 8 English: Weak-Spot Lesson, Level Up","Open the classroom material.","lessons/5si/unit-1/Week%205/Y8-W2L6-LevelUp-IWB.html"]],"intro":"Classroom activities and student materials.","title":"Week 5 materials"};
  lessons["6si-5-materials"] = {"items":[["iwb","Interactive activity","6SI &#183; Survival Skills &#183; Lesson 1 &#183; Danger on the Page","Open the classroom material.","lessons/6si/unit-1/Week%205/6SI_Survival_Skills_L1_Danger_on_the_Page_IWB.html"],["iwb","Interactive activity","6SI &#183; Survival Skills &#183; Lesson 2 &#183; Who Is Telling the Story?","Open the classroom material.","lessons/6si/unit-1/Week%205/6SI_Survival_Skills_L2_Who_Is_Telling_the_Story_IWB.html"],["iwb","Interactive activity","6SI &#183; Survival Skills &#183; Lesson 3 &#183; Write It","Open the classroom material.","lessons/6si/unit-1/Week%205/6SI_Survival_Skills_L3_Write_It_IWB.html"],["worksheet","Student material","Story poster with Sarah 6H SI footer","Open the classroom material.","lessons/6si/unit-1/Week%205/Story%20poster%20with%20Sarah%206H-SI%20footer.png"],["worksheet","Student material","Y7 SS L1 Danger on the Page STUDENT","Open the classroom material.","lessons/6si/unit-1/Week%205/Y7_SS_L1_Danger_on_the_Page_STUDENT.pdf"],["worksheet","Student material","Y7 SS L2 Who Is Telling the Story STUDENT","Open the classroom material.","lessons/6si/unit-1/Week%205/Y7_SS_L2_Who_Is_Telling_the_Story_STUDENT.pdf"],["worksheet","Student material","Y7 SS L3 Write It STUDENT","Open the classroom material.","lessons/6si/unit-1/Week%205/Y7_SS_L3_Write_It_STUDENT.pdf"]],"intro":"Classroom activities and student materials.","title":"Week 5 materials"};
  lessons["6lva-3-materials"] = {"items":[["iwb","Interactive activity","Acrostic Lab","Open the classroom material.","lessons/6lva/unit-1/Week%203/Acrostic%20Lab%20%281%29.html"],["iwb","Interactive activity","Hobby Hour","Open the classroom material.","lessons/6lva/unit-1/Week%203/Hobby%20Hour.html"],["worksheet","Student material","Me and Us Reflection Workbook Page","Open the classroom material.","lessons/6lva/unit-1/Week%203/Me%20and%20Us%20Reflection%20Workbook%20Page.png"],["worksheet","Student material","Me and Us  blank illustrated writing page","Open the classroom material.","lessons/6lva/unit-1/Week%203/Me%20and%20Us_%20blank%20illustrated%20writing%20page.png"],["worksheet","Student material","personalityworksheet","Open the classroom material.","lessons/6lva/unit-1/Week%203/personalityworksheet.pdf"]],"intro":"Classroom activities and student materials.","title":"Week 3 materials"};
  const params = new URLSearchParams(location.search);
  const key = `${params.get("class")}-${params.get("week")}-${params.get("lesson")}`;
  const lesson = lessons[key];
  const className = (params.get("class") || "").toUpperCase();
  const week = params.get("week");
  const fallback = "index.html";
  if (!lesson || !className || !week) { location.replace(fallback); return; }
  const weekPage = `${params.get("class")}-unit-1-week-${week}.html`;
  document.title = `${lesson.title} | ${className} | The Learning Deck`;
  document.getElementById("lesson-kicker").textContent = `${className} · Unit 1 · Week ${week} · ${lesson.title}`;
  document.getElementById("lesson-title").textContent = lesson.title;
  document.getElementById("lesson-intro").textContent = lesson.intro || "Interactive activities and student worksheets.";
  document.getElementById("resource-heading").textContent = `${lesson.title} resources`;
  document.getElementById("back-link").href = weekPage;
  document.getElementById("back-link").firstElementChild.textContent = `${className} · Unit 1 · Week ${week}`;
  document.getElementById("resource-grid").innerHTML = lesson.items.map(([type, label, title, copy, href], index) => `<a class="resource-card resource-${type}" href="${href}" target="_blank" rel="noopener"><span class="number">${String(index + 1).padStart(2, "0")}</span><span class="icon" aria-hidden="true">${type === "iwb" ? "≋" : "◌"}</span><p class="eyebrow">${label}</p><h3>${title}</h3><p>${copy}</p><span class="action">${type === "iwb" ? "Open activity" : "Open worksheet"} <b>→</b></span></a>`).join("");
})();
