import test from 'node:test';
import assert from 'node:assert/strict';
import {makeHandler} from '../netlify/functions/lib/leaderboard-core.mjs';
import {randomUUID} from 'node:crypto';
function setup(){let data=null,version=0,time=100000;const db={async getWithMetadata(){return data?{data:structuredClone(data),etag:String(version)}:null;},async setJSON(k,d,opts){if(opts.onlyIfNew&&data||opts.onlyIfMatch&&opts.onlyIfMatch!==String(version))return {modified:false};data=structuredClone(d);version++;return {modified:true};}};return {handler:makeHandler({store:()=>db,admin:()=> 'teacher-secret',equal:(a,b)=>a===b,now:()=>time}),advance(){time+=16000;}};}
const submission=()=>({name:'SpaceGoat',score:2000,chains:2,seconds:120,completed:12,playerId:randomUUID(),runId:randomUUID()});
function request(method='GET',body,story='missbrill',password){return new Request('https://school.netlify.app/.netlify/functions/annotator-leaderboard?story='+story,{method,headers:{Origin:'https://school.netlify.app','Content-Type':'application/json',...(password?{Authorization:'Bearer '+password}:{})},body:body?JSON.stringify(body):undefined});}
test('save, retrieve, redact private identifiers, idempotent retry',async()=>{const {handler}=setup(),b=submission();assert.equal((await handler(request('POST',b))).status,200);assert.equal((await handler(request('POST',b))).status,200);const d=await (await handler(request())).json();assert.equal(d.rows.length,1);assert.deepEqual(Object.keys(d.rows[0]),['name','score','chains']);});
test('best result survives lower replay; rate limiting',async()=>{const s=setup(),b=submission();await s.handler(request('POST',b));b.runId=randomUUID();b.score=1000;assert.equal((await s.handler(request('POST',b))).status,429);s.advance();await s.handler(request('POST',b));assert.equal((await (await s.handler(request())).json()).rows[0].score,2000);});
test('reject malformed, impossible, unfinished and unsafe names',async()=>{const {handler}=setup();for(const change of [{score:999999},{name:'<script>'},{completed:11},{seconds:1},{chains:13},{playerId:'fake'}])assert.equal((await handler(request('POST',{...submission(),...change}))).status,400);assert.equal((await handler(request('GET',null,'unknown'))).status,400);});
test('unauthorised deletion blocked; teacher deletion works',async()=>{const {handler}=setup();await handler(request('POST',submission()));assert.equal((await handler(request('DELETE'))).status,403);assert.equal((await handler(request('DELETE',null,'missbrill','teacher-secret'))).status,200);assert.equal((await (await handler(request())).json()).rows.length,0);});
test('concurrent different players retained',async()=>{const {handler}=setup();const responses=await Promise.all(Array.from({length:6},()=>handler(request('POST',submission()))));responses.forEach(r=>assert.equal(r.status,200));assert.equal((await (await handler(request())).json()).rows.length,6);});
test('storage failure is not reported as success',async()=>{const handler=makeHandler({store:()=>{throw Error('unavailable');}});assert.equal((await handler(request())).status,503);});
test('cross-origin write blocked',async()=>{const {handler}=setup();const req=request('POST',submission());req.headers.set('Origin','https://other.example');assert.equal((await handler(req)).status,403);});
